defaults : &defaults
  adapter: postgresql
  encoding: utf8
  username: jatgzpcnhnvkhu
  password: l25MsRP1wHVd4jl9cDOfi8mT_8
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: vestibule_development

test:
  <<: *defaults
  database: vestibule_test

production:
  <<: *defaults
  database: de668oaeupvr44
